import { createClient } from './server'
import { customerRegistrationSchema, type CustomerRegistrationInput } from '@/lib/validations/customer'

export interface Customer {
  id: string
  mgp_id: string
  name: string
  email: string | null
  phone: string
  aadhar_number: string | null
  passport_number: string | null
  total_points_earned: number
  available_points: number
  total_points_redeemed: number
  status: string
  created_at: string
  updated_at: string
}

export async function createCustomer(data: CustomerRegistrationInput) {
  const supabase = await createClient()
  
  // Validate input
  const validated = customerRegistrationSchema.parse(data)
  
  // Check for duplicate phone
  const { data: existingPhone } = await supabase
    .from('customers')
    .select('id')
    .eq('phone', validated.phone)
    .single()
  
  if (existingPhone) {
    throw new Error('Phone number already registered')
  }
  
  // Check for duplicate Aadhar if provided
  if (validated.aadhar_number) {
    const { data: existingAadhar } = await supabase
      .from('customers')
      .select('id')
      .eq('aadhar_number', validated.aadhar_number)
      .single()
    
    if (existingAadhar) {
      throw new Error('Aadhar number already registered')
    }
  }
  
  // Check for duplicate Passport if provided
  if (validated.passport_number) {
    const { data: existingPassport } = await supabase
      .from('customers')
      .select('id')
      .eq('passport_number', validated.passport_number)
      .single()
    
    if (existingPassport) {
      throw new Error('Passport number already registered')
    }
  }
  
  // Insert customer (MGP ID will be auto-generated by trigger)
  const { data: customer, error } = await supabase
    .from('customers')
    .insert({
      name: validated.name,
      phone: validated.phone,
      email: validated.email || null,
      aadhar_number: validated.aadhar_number || null,
      passport_number: validated.passport_number || null,
    })
    .select()
    .single()
  
  if (error) {
    throw new Error(`Failed to create customer: ${error.message}`)
  }
  
  return customer as Customer
}

export async function getCustomerById(id: string): Promise<Customer | null> {
  const supabase = await createClient()
  
  const { data, error } = await supabase
    .from('customers')
    .select('*')
    .eq('id', id)
    .single()
  
  if (error || !data) {
    return null
  }
  
  return data as Customer
}

export async function searchCustomers(query: string) {
  const supabase = await createClient()
  
  // Search by phone (exact match)
  if (/^[0-9]{10}$/.test(query)) {
    const { data } = await supabase
      .from('customers')
      .select('id, mgp_id, name, phone, available_points')
      .eq('phone', query)
      .limit(10)
    
    if (data && data.length > 0) {
      return data
    }
  }
  
  // Search by MGP ID (exact match)
  if (query.toUpperCase().startsWith('MGP')) {
    const { data } = await supabase
      .from('customers')
      .select('id, mgp_id, name, phone, available_points')
      .eq('mgp_id', query.toUpperCase())
      .limit(10)
    
    if (data && data.length > 0) {
      return data
    }
  }
  
  // Search by Aadhar if query matches pattern (12 digits)
  const isAadharPattern = /^[0-9]{12}$/.test(query)
  
  if (isAadharPattern) {
    const { data: aadharData } = await supabase
      .from('customers')
      .select('id, mgp_id, name, phone, available_points')
      .eq('aadhar_number', query)
      .limit(10)
    
    if (aadharData && aadharData.length > 0) {
      return aadharData
    }
  }
  
  // Search by name (partial match, case-insensitive)
  // Results sorted by available_points to show customers with more points first
  const { data } = await supabase
    .from('customers')
    .select('id, mgp_id, name, phone, available_points')
    .ilike('name', `%${query}%`)
    .order('available_points', { ascending: false })
    .limit(10)
  
  return data || []
}

